{
 "title": "Chia",
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_filesystem_size_bytes, instance)"
    }
   },
   {
    "name": "mounts",
    "query": {
     "query": "label_values(node_filesystem_size_bytes, mountpoint)"
    }
   },
   {
    "name": "disks",
    "query": {
     "query": "label_values(node_disk_io_time_seconds_total, device)"
    }
   },
   {
    "name": "interfaces",
    "query": {
     "query": "label_values(node_network_receive_bytes_total, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Proofs Found",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_harvester_proofs_total" }
   ]
  },
  {
   "title": "Plots",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_harvester_plots_total", "legendFormat": "Plots" }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$node\",device=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mojo" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_wallet_confirmed_balance_mojo{wallet_id=\"1\"} + chia_wallet_pending_change_mojo{wallet_id=\"1\"}"
    }
   ]
  },
  {
   "title": "Plotting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs",
     "legendFormat": "Plots"
    }
   ]
  },
  {
   "title": "Disk Thoughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",device=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",device=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Search Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(chia_harvester_search_time_bucket[$__rate_interval])) by (le,plots_eligible))",
     "legendFormat": "{{plots_eligible}} Plots Passed Filter"
    }
   ]
  },
  {
   "title": "Search Time Histogram (at least one plot passed filter)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chia_harvester_search_time_bucket{plots_eligible!=\"0\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\", instance=\"$node\"}[$__rate_interval])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$node\",mountpoint=~\"$mounts\"} - node_filesystem_avail_bytes{instance=\"$node\",mountpoint=~\"$mounts\"}) / node_filesystem_size_bytes{instance=\"$node\",mountpoint=~\"$mounts\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_blockchain_sync_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "status",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "chia_peers_count{type=\"1\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "peers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "chia_blockchain_space_bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "netspace",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Usage (last 24hr)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=\"$node\",device=~\"$interfaces\"}[24h]))",
     "legendFormat": " rx"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=\"$node\",device=~\"$interfaces\"}[24h]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"} - node_memory_MemFree_bytes{instance=\"$node\"} - node_memory_Buffers_bytes{instance=\"$node\"} - node_memory_Cached_bytes{instance=\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$node\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Blockchain difficulty",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_blockchain_difficulty",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "difficulty",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Plotting stages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join((plotman_plot_phase_major{} + 0.1 * plotman_plot_phase_minor{}), \"val\", \" \", \"plot_id\", \"run_status\", \"tmp_dir\", \"dst_dir\")",
     "legendFormat": "{{val}}"
    }
   ]
  },
  {
   "title": "Plotting time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(plotman_plot_total_time, \"val\", \" \", \"plot_id\", \"run_status\", \"tmp_dir\", \"dst_dir\")",
     "legendFormat": "{{val}}"
    }
   ]
  },
  {
   "title": "Plotting space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(plotman_plot_tmp_usage, \"val\", \" \", \"plot_id\", \"run_status\", \"tmp_dir\", \"dst_dir\")",
     "legendFormat": "{{val}}"
    }
   ]
  },
  {
   "title": "Plotter Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{job=\"plotter\"}!=\"uniform sort\""
    }
   ]
  },
  {
   "title": "Harvester Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "{job=\"chia\"}|=\"harvester.harvester\"|=\"WARNING\""
    }
   ]
  }
 ]
}